global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['10.155.242.84:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        region: us-west-2
        role_arn: arn:aws:iam::695893684697:role/ecsInstanceRole
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - EC2ContainerService-sling-analytics-DEV-cluster-EcsInstanceAsg-1QHPAQFTDOQU3
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed por
        region: us-west-2
        role_arn: arn:aws:iam::695893684697:role/ecsInstanceRole
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - EC2ContainerService-sling-analytics-DEV-cluster-EcsInstanceAsg-1QHPAQFTDOQU3

